/**
 *FUNÇÕES SÃO BLOCOS QUE PODEM SER REUTILIZADOS
 *FUNÇÕES PODEM OU NÃO RECEBER PARÂMETROS
 * FUNÇÕES PODEM RETORNAR UM VALOR
 * FUNÇÕES  PODEM SER ANÔNIMAS
 */
// DECLARAÇÃO DE FUNÇÃO
function dizOla() {
  alert('Olá')
}
// INVOCAÇÃO DE FUNÇÃO
dizOlá()